server:
  port: 9991

spring:
  application:
    name: hello-springboot-screw
  datasource:
    url: jdbc:mysql://10.0.99.142:3306/ccdcsm-apm?serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    xa:
      properties:
        useInformationSchema: true