server:
  port: 8012

spring:
  application:
    name: hello-springboot-kaptcha

# 配置redis
redis:
  client-type: jedis
  host: 192.168.5.179
  password: 123456
  port: 6379
  jedis:
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 100
      # 连接池中的最大空闲连接
      max-idle: 100
      # 连接池中的最小空闲连接
      min-idle: 100
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 60000
